# Generated by Django 6.0.3 on 2026-03-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('school', 'School Supplies'), ('clothing', 'Clothing'), ('sports', 'Sports Gear'), ('accessories', 'Accessories'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location_found', models.CharField(max_length=120)),
                ('date_found', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_photos/')),
                ('submitted_by_name', models.CharField(max_length=100)),
                ('submitted_by_email', models.EmailField(max_length=254)),
                ('submitted_by_phone', models.CharField(blank=True, max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('claimed', 'Claimed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=100)),
                ('claimant_email', models.EmailField(max_length=254)),
                ('claimant_phone', models.CharField(blank=True, max_length=25)),
                ('proof_of_ownership', models.TextField()),
                ('additional_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='lostfound.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
